# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gbuuTZUwV92h21DhtRQPfaxzpGzpFm-r
"""


import plotly.express as px
import pandas as pd

df=pd.read_csv('/content/message_data.csv')

fig = px.line(df, x='message_time', y='message_id', title='Percentage of Daily Messages Sent by New Users')
fig.show()

